name: Deploy-to-dev

on:
  push:
    branches:
      - dev
jobs:
  Build-and-Deploy:
    runs-on: 35.236.219.144
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ls -la && npm install && npm run build && ls -ls | grep dist
      - name: SSH server 
        run: echo "${{ secrets.SSH_KEY }}" > ./key && chmod 600 ./key
      - name: Copy build to server
        run: ssh -i key aman@35.236.219.144 && cd / && ls 
