name: Deploy-to-dev

on:
  push:
    branches:
      - dev
jobs:
  Build-and-Deploy:
    runs-on: 35.236.219.144
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ls -la && sudo npm install && sudo npm run build && ls -ls | grep dist
