name: script-test

on:
  push:
    branches:
      - feature-cicd
jobs:
  Build-and-Deploy:
    runs-on: 10.0.1.202
    steps:
      - name: SSH server 
        run: |
          echo "${{ secrets.FEATURE_KEY }}" > ./key && chmod 600 ./key 
          ssh -i key ec2-user@10.0.12.243  "
          git@github.com:iamvashistaman/devops.git
          cd devops/bloomcare/ && chmod +x test.sh
          ./test.sh"
