name: script-test

on:
  push:
    branches:
      - feature-cicd
jobs:
  Build-and-Deploy:
    runs-on: 10.0.1.202
    steps:
      - uses: actions/checkout@v2
      - name: SSH server 
        run: |
          echo "${{ secrets.FEATURE_KEY }}" > ./key && chmod 600 ./key 
          ssh -i key ec2-user@10.0.12.243 "sudo su - pm2
          git clone git@github.com:iamvashistaman/devops.git
          cd devops/scripts/ && chmod +x test.sh
          ./test.sh"

