name: script-test

on:
  push:
    branches:
      - feature-cicd
jobs:
  Build-and-Deploy:
    runs-on: 10.0.1.202
    steps:
      - name: SSH server 
        run: |
          echo "${{ secrets.FEATURE_KEY }}" > ./key && chmod 600 ./key 
          ssh -i key ec2-user@10.0.12.243  "
          git clone git@github.com:iamvashistaman/devops.git
          sudo mv devops/ /apps/pm2/
          sudo su && cd /apps/pm2 && chown -R pm2:pm2 devops
          su - pm2
          cd devops/scripts/ && chmod +x test.sh
          ./test.sh 
          cd ~ && rm -rf devops"
