name: script-test

on:
  workflow_run:
    workflows: ["script-test"]
    types:
      - requested
jobs:
  Build-and-Deploy:
    runs-on: 10.0.1.202
    steps:
      - name: SSH server 
        run: |
          echo "${{ secrets.FEATURE_KEY }}" > ./key && chmod 600 ./key 
          ssh -i key ec2-user@10.0.12.243  "
          git clone git@github.com:iamvashistaman/devops.git
          sudo mv devops /apps/script/
          cd /apps/script 
          sudo chown -R pm2:pm2 devops
          sudo su pm2
          cd devops/scripts/ && sudo chmod +x test.sh
          ./test.sh 
          cd /apps/script/
          sudo rm -rf devops " 
